project: SAGE_GCN_hyperparameter_tuning_cora_icassp_undirected
method: grid
metric:
  name: valid_acc
  goal: maximize
parameters:
  batch_size:
    values: [1024]
  optimizer_type:
    values: ['Adam']
  learning_rate:
    values: [0.001, 0.0001]
  weight_decay:
    values: [0.001, 0.0001]
  num_hidden_layers:
    values: [1, 2, 3]
  hidden_dim:
    values: [64, 128]
  dataset_name:
    values: ['CoraGraphDataset']
  sample_rate:
    values: [0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0]
  num_epochs:
    values: [200, 300]
  trace_type:
    values: ['Feature']
  exclusion_type:
    values: ['Largest']
  model_type:
    values: ['SAGE', 'GCN']
  activation_type:
    values: ['Relu']
